steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/hello-war:$COMMIT_SHA", "-t", "gcr.io/$PROJECT_ID/hello-war:latest", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/hello-war:$COMMIT_SHA"]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/hello-war:latest"]
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - run
  - --image=gcr.io/$PROJECT_ID/hello-war:latest
  - --location=us-central1-a
  - --cluster=ad-k8s-cluster
  - --app=hello-world-war
  - --expose=8080
  - --namespace=default
#- name: 'gcr.io/cloud-builders/kubectl'
#  args: ['expose', 'deployment', 'hello-war', '--type=LoadBalancer', '--port=80', '--target-port=8080']
