steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
- name: 'ubuntu'
  args: ['ls']
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/my-project/hello-war:$REVISION_ID", "."]